name: BungeeCordNitrox
authors: [1BlueNitrox - Felix]
main: me.bluenitrox.main.Main
version: 1.0

commands:
  shop:
  hero:
  master:
  dc:
  ping:
  bc:
  yt:
    aliases:
      - youtube
      - youtuber
  wartung:
  motd: